Repository elastic/apm-pipeline-library, pull requests merged in 2021-12, with the labels that each got.

#1421 Support for DisableConcurrentBuildsJobProperty
  pom.xml
  resources/github-comment-markdown.template
  src/co/elastic/NotificationManager.groovy
  src/test/groovy/NotificationManagerStepTests.groovy
  src/test/groovy/co/elastic/mock/RunMock.groovy
Labels: enhancement, groovy, ready-to-merge

#1431 [mergify] use merge queue
  .mergify.yml
Labels: chore, ready-to-merge

#1427 Support for the AWS cli env
  local/configs/jenkins.yaml
  src/test/groovy/ApmBasePipelineTest.groovy
  src/test/groovy/WithAWSEnvStepTests.groovy
  src/test/resources/jobs/withAWSEnv.dsl
  vars/withAWSEnv.groovy
  vars/withAWSEnv.txt
Labels: enhancement, groovy, master, ready-to-merge

#1432 reduce sleep from 5 minutes to 2 minutes
  vars/githubWorkflowRun.groovy
Labels: enhancement, groovy, ready-to-merge

#1434 fix: Fix docker images
  .ci/build-docker-images.groovy
  .ci/docker/apache-ant/Dockerfile
  .ci/docker/kibana-devmode/Dockerfile
  .ci/docker/kibana-yarn/Dockerfile
  .ci/jobDSL/jobs/apm-ci/apm-shared/docker-images/build_docker_images.groovy
Labels: bug, automation, ci, Team:Automation

#1417 Remove support for index jenkins-build
  local/Makefile
  resources/jenkins-builds-mapping.json
  resources/scripts/generate-build-data.sh
  src/test/groovy/GenerateBuildDataIntegrationTests.groovy
  src/test/groovy/NotifyBuildResultStepTests.groovy
  src/test/resources/__files/body-blue-rest-organizations-jenkins-pipelines-it-getBuildInfoJsonFiles-cobertura-runs-1-log-iMg03.txt
  src/test/resources/mappings/blue_rest_organizations_jenkins_pipelines_it_getbuildinfojsonfiles_abort_runs_1_log-8af6681b-d3a1-4a7e-9a4f-217d6ff17541.json
  src/test/resources/mappings/blue_rest_organizations_jenkins_pipelines_it_getbuildinfojsonfiles_abort_runs_1_tests-fa9db0ea-31b4-4dea-8ff2-529b6ae1051b.json
  src/test/resources/mappings/blue_rest_organizations_jenkins_pipelines_it_getbuildinfojsonfiles_empty_runs_1_tests-c1fa48c7-e337-4393-998a-7040168b6d4c.json
  src/test/resources/mappings/blue_rest_organizations_jenkins_pipelines_it_getbuildinfojsonfiles_error_runs_1_log-844f7f75-8fcf-41e4-80f8-4fa1bd4be506.json
  src/test/resources/mappings/blue_rest_organizations_jenkins_pipelines_it_getbuildinfojsonfiles_error_runs_1_tests-8e222025-8ab8-4bba-94b5-2b6a11127185.json
  src/test/resources/mappings/blue_rest_organizations_jenkins_pipelines_it_getbuildinfojsonfiles_multitestfailures_runs_1_log-f78c0b1b-c892-4c95-8b42-0fd3a0cf5204.json
  src/test/resources/mappings/blue_rest_organizations_jenkins_pipelines_it_getbuildinfojsonfiles_multitestfailures_runs_1_tests-78b81daa-a2cd-4364-8d61-7bb0ea569daa.json
  src/test/resources/mappings/blue_rest_organizations_jenkins_pipelines_it_getbuildinfojsonfiles_success_runs_1_log-dd0fd32c-55a5-45e3-880c-25d188dfde63.json
  src/test/resources/mappings/blue_rest_organizations_jenkins_pipelines_it_getbuildinfojsonfiles_success_runs_1_tests-8aa319a8-dd29-45f0-b369-47737f0225fa.json
  src/test/resources/mappings/blue_rest_organizations_jenkins_pipelines_it_getbuildinfojsonfiles_unstable_runs_1_log-5cd4b2df-95a8-49af-8443-9732239d5959.json
  src/test/resources/mappings/blue_rest_organizations_jenkins_pipelines_it_getbuildinfojsonfiles_unstable_runs_1_tests-134d5192-5383-40c8-9570-5a258d73f950.json
  src/test/resources/mappings/mapping-blue-rest-organizations-jenkins-pipelines-it-getBuildInfoJsonFiles-cobertura-runs-1-tests-C8sFC.json
  src/test/resources/watcher-output.json
  vars/notifyBuildResult.groovy
Labels: automation, chore, groovy, master, ready-to-merge

#1436 fix: add HOME folders to the PATH
  .ci/build-docker-images.groovy
Labels: bug, automation, ci, Team:Automation

#1440 Abort on PR basis if an old running build
  .ci/Jenkinsfile
  resources/JenkinsfileTemplate.groovy
  vars/README.md
  vars/cancelPreviousRunningBuilds.groovy
  vars/cancelPreviousRunningBuilds.txt
Labels: automation, ci, groovy

#1438 only if changes in the files
  .ci/Jenkinsfile
Labels: automation, ci

#1392 feat: publish pytest_otel
  resources/scripts/pytest_otel/.editorconfig
  resources/scripts/pytest_otel/.gitignore
  resources/scripts/pytest_otel/.pre-commit-config.yaml
  resources/scripts/pytest_otel/LICENSE.txt
  resources/scripts/pytest_otel/Makefile
  resources/scripts/pytest_otel/README.md
  resources/scripts/pytest_otel/pyproject.toml
  resources/scripts/pytest_otel/pytest_otel.py
  resources/scripts/pytest_otel/requirements.txt
  resources/scripts/pytest_otel/setup.cfg
  resources/scripts/pytest_otel/setup.py
  resources/scripts/pytest_otel/src/pytest_otel/__init__.py
  resources/scripts/pytest_otel/test_pytest_otel.py
  resources/scripts/pytest_otel/tests/docker-compose.yml
  resources/scripts/pytest_otel/tests/it/conftest.py
  resources/scripts/pytest_otel/tests/it/test_basic_plugin.py
  resources/scripts/pytest_otel/tests/it/test_failure_code_plugin.py
  resources/scripts/pytest_otel/tests/it/test_failure_plugin.py
  resources/scripts/pytest_otel/tests/it/test_skip_plugin.py
  resources/scripts/pytest_otel/tests/it/test_success_plugin.py
  resources/scripts/pytest_otel/tests/it/test_xfail_no_run_plugin.py
  resources/scripts/pytest_otel/tests/it/test_xfail_plugin.py
  resources/scripts/pytest_otel/tests/it/utils/__init__.py
  resources/scripts/pytest_otel/tests/otel-collector.yaml
  resources/scripts/pytest_otel/tests/test_pytest_otel.py
  resources/scripts/pytest_otel/tox.ini
Labels: enhancement, ci, Team:Automation

#1435 Allow to customise the vault token
  src/test/groovy/WithAWSEnvStepTests.groovy
  vars/withAWSEnv.groovy
  vars/withAWSEnv.txt
Labels: enhancement, groovy, ready-to-merge

#1442 fix: latest issues on Docker images
  .ci/build-docker-images.groovy
  .ci/jobDSL/jobs/apm-ci/apm-shared/docker-images/build_docker_images.groovy
Labels: bug, automation, ci, Team:Automation

#1452 fix: fix pytest_otel authentification
  resources/scripts/pytest_otel/README.md
  resources/scripts/pytest_otel/docs/demos/elastic/demo.env
  resources/scripts/pytest_otel/docs/demos/elastic/docker-compose.yml
  resources/scripts/pytest_otel/docs/demos/jaeger/docker-compose.yml
  resources/scripts/pytest_otel/requirements.txt
  resources/scripts/pytest_otel/setup.cfg
Labels: bug, Team:Automation

#1453 Default vault secrets for getVaultSecret to dynamically inspect the CI controller
  src/test/groovy/ApmBasePipelineTest.groovy
  src/test/groovy/GetVaultSecretStepTests.groovy
  vars/getVaultSecret.groovy
Labels: enhancement, groovy, ready-to-merge

#1454 Support the case when OTEL plugin has not been configured
  src/test/groovy/ApmBasePipelineTest.groovy
  src/test/groovy/WithOtelEnvStepTests.groovy
  src/test/groovy/co/elastic/mock/OtelHelperMock.groovy
  vars/withOtelEnv.groovy
Labels: groovy

#1457 manually bump releases
  .ci/updateStackReleaseVersion.groovy
Labels: automation, ci

#1459 [automation] Update Elastic stack release version source of truth
  resources/versions/releases.properties
Labels: automation

#1461 [automation] Update Elastic stack release version 7.16.1 7.16.2
  .ci/packer_cache.sh
  vars/filebeat.groovy
  vars/metricbeat.groovy
  vars/stackVersions.groovy
Labels: automation, ci, groovy, dependency

#1456 Support for no credentials but endpoint
  src/test/groovy/WithOtelEnvStepTests.groovy
  vars/withOtelEnv.groovy
Labels: groovy

#1463 Add 7.17 branch versions
  .ci/updateStackReleaseVersion.groovy
Labels: automation, ci, ready-to-merge

#1462 fix: improve attributes access
  resources/scripts/pytest_otel/setup.cfg
  resources/scripts/pytest_otel/src/pytest_otel/__init__.py
Labels: bug, Team:Automation

#1458 [jjbb][main] neutral naming for observability-robots
  .ci/buildDockerImages.groovy
  .ci/jobs/gather-ci-metrics-pipeline.yml
Labels: automation, ci

#1465 Opbeans: rename master for main
  .ci/dockerImagesOpbeans.groovy
  .ci/jobDSL/jobs/apm-ci/apm-shared/docker-images/build_docker_images.groovy
  src/test/groovy/OpbeansPipelineStepTests.groovy
  vars/opbeansPipeline.groovy
Labels: automation, ci, groovy

#1466 obs-robots main branch
  .ci/buildDockerImages.groovy
Labels: automation, ci

#1471 docker: no cache flag when building the image
  .ci/buildDockerImages.groovy
Labels: bug, automation, ci

#1469 Bump 7.16.2 and 6.8.22 versions
  .ci/updateStackReleaseVersion.groovy
Labels: automation, ci

#1470 [automation] Update Elastic stack release version source of truth
  .pre-commit-config.yaml
  resources/versions/releases.properties
Labels: automation

#1476 Beats: notify 7 next minor branch and 7 current branch
  .ci/schedule-weekly.groovy
Labels: automation, ci

#1478 Main leftovers
  .ci/buildBeatsDockerImages.groovy
  .ci/bumpGoReleaseVersion.groovy
  .ci/bumpStackReleaseVersion.groovy
  .ci/updateStackReleaseVersion.groovy
  .ci/validateWorkersBeatsCi.groovy
  resources/scripts/artifacts-api-latest-versions.sh
  vars/README.md
  vars/buildKibanaDockerImage.groovy
  vars/buildKibanaDockerImage.txt
  vars/runE2E.txt
Labels: automation, ci, groovy

#1479 Support main for e2e-testing
  vars/runE2E.groovy
Labels: bug, groovy

#1481 [automation] Update Elastic stack release version 7.16.1 7.17.0
  vars/stackVersions.groovy
Labels: automation, groovy, dependency

#1485 [automation] Update Elastic stack release version source of truth
  resources/versions/releases.properties
Labels: automation

#1486 [automation] Update Elastic stack release version 7.16.2 7.17.0
  .ci/packer_cache.sh
  vars/filebeat.groovy
  vars/metricbeat.groovy
  vars/stackVersions.groovy
Labels: automation, ci, groovy, dependency
