Repository elastic/apm-pipeline-library, pull requests merged in 2022-09, with the labels that each got.

#1863 dependabot: less often
  .github/dependabot.yml
Labels: automation

#1859 test-infra: update ephemeral workers and osx static workers
  .ci/validateWorkersBeatsCi.groovy
Labels: automation, ci

#1841 pytest_otel: add hard dependencies
  resources/scripts/pytest_otel/README.md
  resources/scripts/pytest_otel/pyproject.toml
  resources/scripts/pytest_otel/setup.cfg
Labels: ready-to-merge

#1862 Fallback for isBranchUnifiedReleaseAvailable
  src/test/groovy/IsBranchUnifiedReleaseAvailableStepTests.groovy
  vars/isBranchUnifiedReleaseAvailable.groovy
Labels: enhancement, groovy

#1866 ci: pre-commit in Jenkins
  .ci/Jenkinsfile
  .github/workflows/opentelemetry.yml
  .github/workflows/pre-commit.yml
Labels: automation, ci

#1868 [automation] Update go release version 1.19.1
  vars/goDefaultVersion.groovy
Labels: automation, groovy, dependency

#1871 feat: add pytest_otel dependabot configuration
  .github/dependabot.yml
Labels: enhancement, automation, Team:Automation

#1869 cosmetic: github comment section to be collapsed
  resources/commands-github-comment-markdown.template
Labels: chore

#1880 feat: pytest_otel workflow
  .github/CODEOWNERS
  .github/workflows/pytest_otel.yml
Labels: enhancement, automation, ci, Team:Automation

#1881 go 1.18 for apm pipeline
  .ci/.bump-go-release-version.yml
  vars/goDefaultVersion.groovy
Labels: groovy

#1872 feat: add github-actions[bot] to authorized bot
  vars/githubPrCheckApproved.groovy
Labels: enhancement, groovy, Team:Automation

#1882 fix: path filter incorrect
  .github/workflows/pytest_otel.yml
Labels: bug, Team:Automation

#1870 [automation] Update Elastic stack release version source of truth
  resources/versions/releases.properties
Labels: automation

#1885 [automation] Update Elastic stack release version 8.4.2 8.4.2
  .ci/packer_cache.sh
  vars/filebeat.groovy
  vars/metricbeat.groovy
Labels: automation, ci, groovy, dependency

#1883 [automation] Update go release version 1.18.6
  vars/goDefaultVersion.groovy
Labels: automation, groovy, dependency

#1886 chore: delete some jobs
  .ci/jobDSL/jobs/apm-ci/apm-shared/oblt-test-env/edge_lite.groovy
  .ci/jobDSL/jobs/apm-ci/apm-shared/oblt-test-env/test_mbp.groovy
  .ci/jobDSL/jobs/apm-ci/apm-shared/oblt-test-env/updatecli.groovy
Labels: chore

#1887 [automation] Update Elastic stack release version source of truth
  resources/versions/releases.properties
Labels: automation

#1888 [automation] Update Elastic stack release version source of truth
  resources/versions/releases.properties
Labels: automation

#1890 chore: bump Otel 1.12.0
  .gitignore
  resources/scripts/pytest_otel/Makefile
  resources/scripts/pytest_otel/mypy.ini
  resources/scripts/pytest_otel/pyproject.toml
  resources/scripts/pytest_otel/requirements.txt
  resources/scripts/pytest_otel/setup.cfg
  resources/scripts/pytest_otel/tests/docker-compose.yml
Labels: chore

#1896 [automation] Update Elastic stack release version source of truth
  resources/versions/releases.properties
Labels: automation

#1898 docs: Pytest otel 1.2.0 release notes
  resources/scripts/pytest_otel/CHANGELOG.md
  resources/scripts/pytest_otel/mypy.ini
  resources/scripts/pytest_otel/setup.cfg
  resources/scripts/pytest_otel/tox.ini
Labels: docs, Team:Automation

#1899 docs: update readme with the new Otel versions required
  resources/scripts/pytest_otel/README.md
Labels: docs, Team:Automation

#1900 fix: bump pytest_otel version to 1.2.1
  resources/scripts/pytest_otel/CHANGELOG.md
  resources/scripts/pytest_otel/setup.cfg
Labels: chore, Team:Automation

#1901 fix: install weel before to make a package
  resources/scripts/pytest_otel/CHANGELOG.md
  resources/scripts/pytest_otel/Makefile
Labels: bug, Team:Automation

#1897 chore: remove update stack
  .ci/.bump-stack-release-version.yml
Labels: chore, Team:Automation

#1902 [automation] Update Elastic stack release version 8.4.3 8.5.0
  .ci/packer_cache.sh
  vars/filebeat.groovy
  vars/metricbeat.groovy
Labels: automation, ci, groovy, dependency

#1903 fix: Remove "Integration Tests" stage from opbeansPipeline
  src/test/groovy/OpbeansPipelineStepTests.groovy
  vars/opbeansPipeline.groovy
Labels: groovy

#1905 Revert "[automation] Update Elastic stack release version 8.4.3 8.5.0"
  .ci/packer_cache.sh
  vars/filebeat.groovy
  vars/metricbeat.groovy
Labels: automation, ci, groovy
