Repository elastic/apm-pipeline-library, pull requests merged in 2022-03, with the labels that each got.

#1561 Bump to the next patch release
  .ci/updateStackReleaseVersion.groovy
Labels: automation, ci, on-hold

#1572 GitHub commands for the elastic-agent project
  src/co/elastic/NotificationManager.groovy
Labels: enhancement, groovy

#1571 fix: Node.js install issues
  resources/scripts/build-kibana-docker-image.sh
Labels: bug, Team:Automation

#1565 [automation] 7.17.1 is now available
  .ci/updateStackReleaseVersion.groovy
Labels: automation, ci

#1573 [automation] Update Elastic stack release version source of truth
  resources/versions/releases.properties
Labels: automation

#1574 automation: support 8 and 7 major branches
  .ci/bumpStackReleaseVersion.groovy
Labels: automation, ci

#1576 fix: update maintenance branches
  .ci/.bump-stack-version.yml
Labels: chore

#1579 [automation] Update Elastic stack release version 8.0.1 8.2.0
  .ci/packer_cache.sh
  vars/filebeat.groovy
  vars/metricbeat.groovy
Labels: automation, ci, groovy, dependency

#1577 weekly: refactor with getBranchesFromAliases
  .ci/schedule-weekly.groovy
Labels: automation, ci

#1581 jobdsl: add daily and ci-metrics jobs in fleet-ci
  .ci/fleet-ci-schedule-daily.groovy
  .ci/jobDSL/jobs/fleet-ci/fleet-shared/fleet-schedule-daily.groovy
  .ci/jobDSL/jobs/fleet-ci/fleet-shared/gather-ci-metrics-pipeline.groovy
Labels: automation, ci

#1582 jobdsl: only underscores
  .ci/jobDSL/jobs/fleet-ci/fleet-shared/fleet_schedule_daily.groovy
  .ci/jobDSL/jobs/fleet-ci/fleet-shared/gather_ci_metrics_pipeline.groovy
Labels: bug

#1592 ci: golang onboarding, bump version
  .ci/.bump-go-release-version.yml
Labels: chore

#1595 [automation] Update Elastic stack release version source of truth
  resources/versions/releases.properties
Labels: automation

#1597 Fix OTEL_ELASTIC_URL with spaces
  resources/github-comment-markdown.template
  resources/slack-markdown.template
  src/test/groovy/GenerateBuildDataIntegrationTests.groovy
  src/test/groovy/NotificationManagerStepTests.groovy
Labels: bug, groovy

#1596 [automation] Update Elastic stack release version 8.1.0 8.2.0
  .ci/packer_cache.sh
  vars/filebeat.groovy
  vars/metricbeat.groovy
Labels: automation, ci, groovy, dependency

#1588 github command: test on windows
  src/co/elastic/NotificationManager.groovy
Labels: groovy

#1591 bump automation for golang versions
  .ci/.bump-go-release-version.yml
  .ci/bumpGoReleaseVersion.groovy
Labels: automation, ci

#1589 Add Golang changelog in the PR
  .ci/bumpGoReleaseVersion.groovy
Labels: enhancement, automation, ci

#1590 jobdsl: avoid delete
  .ci/fleet-ci-jobdsl-generator.groovy
Labels: automation, ci

#1584 [automation] Update go release version 1.17.8
  vars/goDefaultVersion.groovy
Labels: automation, groovy, dependency

#1543 chore: use new junit2otel step
  .ci/Jenkinsfile
  resources/scripts/junit2otel.sh
  src/test/groovy/ApmBasePipelineTest.groovy
  src/test/groovy/Junit2OtelStepTests.groovy
  vars/junit2otel.groovy
Labels: enhancement, automation, ci, groovy

#1600 fix golang bump with misleading go version in description
  .ci/bumpGoReleaseVersion.groovy
Labels: bug, automation, ci, ready-to-merge

#1601 getBranchesFromAliases : support minor index alias
  src/test/groovy/GetBranchesFromAliasesStepTests.groovy
  vars/README.md
  vars/getBranchesFromAliases.groovy
  vars/getBranchesFromAliases.txt
Labels: enhancement, groovy

#1602 Use https rather than git
  src/test/groovy/GoVersionStepTests.groovy
  vars/goVersion.groovy
Labels: bug, groovy

#1604 fix <minor-1> manipulation
  src/test/groovy/GetBranchesFromAliasesStepTests.groovy
  vars/getBranchesFromAliases.groovy
Labels: bug, groovy

#1605 fix tar with 7z without extension
  vars/tar.groovy
Labels: bug, groovy

#1609 email bump automation relies on testing/environments/snapshot.yml
  resources/scripts/generate-email-template-if-no-recent-changes.sh
Labels: automation, chore, ready-to-merge

#1608 If no aborted then notify the pipeline syntax error
  resources/github-comment-markdown.template
  src/test/groovy/NotificationManagerStepTests.groovy
Labels: groovy, ready-to-merge

#1610 withGCPEnv: solve path separator on windows
  .ci/Jenkinsfile
  src/co/elastic/NotificationManager.groovy
  src/test/groovy/WithGCPEnvStepTests.groovy
  vars/withGCPEnv.groovy
Labels: automation, ci, groovy

#1613 Fix: node version install
  .ci/docker/kibana-yarn/Dockerfile
  resources/scripts/build-kibana-docker-image.sh
Labels: bug, ci, Team:Automation

#1611 weekly test report for elastic-agent and e2e-testing
  .ci/schedule-weekly.groovy
Labels: automation, ci

#1617 fix generateBuildReport: net.sf.json.JSONNull
  resources/github-comment-markdown.template
Labels: bug

#1615 refactor: weekly email based on yaml file
  .ci/.weekly-tests-email.yml
  .ci/schedule-weekly.groovy
Labels: enhancement, automation, ci

#1621 fix: show traces only on debug mode
  resources/scripts/pytest_otel/CHANGELOG.md
  resources/scripts/pytest_otel/setup.cfg
  resources/scripts/pytest_otel/src/pytest_otel/__init__.py
Labels: bug, Team:Automation

#1623 fix: remove pytest timming import
  resources/scripts/pytest_otel/src/pytest_otel/__init__.py
Labels: bug, Team:Automation

#1624 chore: Pytest otel release
  resources/scripts/pytest_otel/CHANGELOG.md
  resources/scripts/pytest_otel/setup.cfg
Labels: chore, Team:Automation

#1625 fix: add Docker, buildx, and Docker compose to the Docker image
  .ci/docker/kibana-yarn/Dockerfile
Labels: bug, ci, Team:Automation

#1627 releaseManagerAnalyser and releaseManagerNotification step
  resources/scripts/release-manager-analyser.sh
  src/test/groovy/ApmBasePipelineTest.groovy
  src/test/groovy/ReleaseManagerAnalyserStepTests.groovy
  src/test/groovy/ReleaseManagerNotificationStepTests.groovy
  vars/releaseManagerAnalyser.groovy
  vars/releaseManagerAnalyser.txt
  vars/releaseManagerNotification.groovy
  vars/releaseManagerNotification.txt
Labels: enhancement, groovy

#1630 feat: Update OpenTelemetry SDK to 1.10.0
  resources/scripts/pytest_otel/README.md
  resources/scripts/pytest_otel/requirements.txt
  resources/scripts/pytest_otel/setup.cfg
  resources/scripts/pytest_otel/src/pytest_otel/__init__.py
Labels: Team:Automation

#1628 Add releaseManager step
  resources/scripts/release-manager.sh
  src/test/groovy/ReleaseManagerAnalyserStepTests.groovy
  src/test/groovy/ReleaseManagerStepTests.groovy
  vars/README.md
  vars/releaseManager.groovy
  vars/releaseManager.txt
  vars/releaseManagerAnalyser.groovy
Labels: enhancement, groovy

#1633 Automate release versions for 7 and last 8
  .ci/updateStackReleaseVersion.groovy
Labels: automation, ci
