Repository elastic/apm-pipeline-library, pull requests merged in 2022-10, with the labels that each got.

#1911 Honour archiveOnlyOnFail in metricbeat
  src/test/groovy/MetricbeatStepTests.groovy
  src/test/resources/metricbeatTest_2/metricbeat_container_worker-0676d01d9601f8191.json
  vars/metricbeat.groovy
  vars/metricbeat.txt
Labels: enhancement, groovy

#1908 [automation] Update Elastic stack release version 8.4.3 8.5.0
  .ci/packer_cache.sh
  vars/filebeat.groovy
  vars/metricbeat.groovy
Labels: automation, ci, groovy, dependency

#1912 [automation] Update go release version 1.18.7
  vars/goDefaultVersion.groovy
Labels: automation, groovy, dependency

#1918 action: release drafter for git tag releases
  .ci/Jenkinsfile
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
  CHANGELOG.md
  resources/scripts/jenkins/release-notes.sh
Labels: automation, ci, chore

#1919 feat: add GitHub Actions library
  .github/actions/docker-login/action.yml
  .github/actions/github-token/action.yml
  .github/actions/slack-message/action.yml
Labels: enhancement, Team:Automation

#1921 fix: delete src/pytest_otel.egg-info on clean
  resources/scripts/pytest_otel/Makefile
Labels: bug, Team:Automation

#1922 fix: remove branches jobs creation
  .ci/jobs/apm-pipeline-library-mbp.yml
Labels: enhancement, Team:Automation
