Repository elastic/apm-pipeline-library, pull requests merged in 2022-07, with the labels that each got.

#1758 [automation] Update Elastic stack release version source of truth
  resources/versions/releases.properties
Labels: automation

#1757 automation: enable extended description for the Golang autobump
  .ci/.bump-go-release-version.yml
  .ci/bumpGoReleaseVersion.groovy
Labels: enhancement, automation, ci, ready-to-merge

#1759 [automation] Update Elastic stack release version 8.3.1 8.3.1
  .ci/packer_cache.sh
  vars/filebeat.groovy
  vars/metricbeat.groovy
Labels: automation, ci, groovy, dependency

#1760 ci: skip default checkout
  .ci/Jenkinsfile
Labels: automation, ci, ready-to-merge

#1755 feat: job to manage the edge-lite cluster
  .ci/jobDSL/jobs/apm-ci/apm-shared/oblt-test-env/destroy_oblt_cluster.groovy
  .ci/jobDSL/jobs/apm-ci/apm-shared/oblt-test-env/edge-lite.groovy
  .ci/jobDSL/jobs/apm-ci/apm-shared/oblt-test-env/update_oblt_cluster.groovy
Labels: enhancement, Team:Automation

#1614 feat: pod templates
  resources/pods/dind-golang.yml
  resources/pods/dind-python.yml
  resources/pods/golang.yml
  resources/pods/python.yml
Labels: enhancement, ci, Team:Automation

#1762 fix: job name can not contain `-`
  .ci/jobDSL/jobs/apm-ci/apm-shared/oblt-test-env/edge_lite.groovy
Labels: bug, Team:Automation

#1766 [automation] Update Elastic stack release version source of truth
  resources/versions/releases.properties
Labels: automation

#1773 [automation] Update Elastic stack release version 8.3.2 8.3.2
  .ci/packer_cache.sh
  vars/filebeat.groovy
  vars/metricbeat.groovy
Labels: automation, ci, groovy, dependency

#1774 Support for isDarwin step
  src/test/groovy/ApmBasePipelineTest.groovy
  src/test/groovy/IsDarwinStepTests.groovy
  vars/isDarwin.groovy
  vars/isDarwin.txt
Labels: groovy

#1788 [automation] Update go release version 1.18.4
  vars/goDefaultVersion.groovy
Labels: automation, groovy, dependency

#1775 ci: enable k8s workers
  .ci/bumpGoReleaseVersion.groovy
  .ci/bumpStackReleaseVersion.groovy
  .ci/chatops.groovy
  .ci/fleet-ci-schedule-daily.groovy
  .ci/schedule-daily.groovy
  .ci/schedule-weekly.groovy
  .ci/updateStackReleaseVersion.groovy
  .ci/validateWorkersBeatsCi.groovy
Labels: automation, ci, ready-to-merge

#1776 feat: add Generic Webhook trigger configuration
  .ci/jobDSL/jobs/apm-ci/apm-shared/oblt-test-env/edge_lite.groovy
  .ci/jobDSL/jobs/apm-ci/apm-shared/oblt-test-env/manage_user_oblt_clusters.groovy
Labels: enhancement, Team:Automation

#1799 Prepare jenkins-agent with the required tools
  .ci/docker/Makefile
  .ci/docker/jenkins-agent/Dockerfile
  .ci/docker/tests/tests_without_run.bats
  .ci/jobDSL/jobs/apm-ci/apm-shared/docker-images/build_docker_images.groovy
Labels: enhancement, automation

#1801 Trigger docker images more frequently
  .ci/jobDSL/jobs/apm-ci/apm-shared/oblt-test-env/stack_docker_images.groovy
Labels: Team:Automation

#1802 Remove mention of "/hey-apm" from apm-server
  src/co/elastic/NotificationManager.groovy
Labels: groovy

#1804 fix: update the pytest_otel demo
  resources/scripts/pytest_otel/docs/demos/jaeger/config/otel-collector-config.yaml
  resources/scripts/pytest_otel/docs/demos/jaeger/docker-compose.yml
Labels: bug

#1806 ci: use cloud workers
  .ci/updateStackReleaseVersion.groovy
Labels: automation, ci

#1805 Fix copyArtifacts for generateGoBenchmarkDiff to use the folder structure
  vars/generateGoBenchmarkDiff.groovy
Labels: bug, groovy

#1816 ci: fix the workspace setup
  .ci/Jenkinsfile
Labels: bug, automation, ci

#1821 fix empty list of 7 releases
  .ci/updateStackReleaseVersion.groovy
Labels: automation, ci

#1824 fix unified-release branch check
  src/test/groovy/IsBranchUnifiedReleaseAvailableStepTests.groovy
  vars/isBranchUnifiedReleaseAvailable.groovy
Labels: groovy

#1827 Revert ci: enable k8s workers (#1775)"
  .ci/bumpGoReleaseVersion.groovy
  .ci/bumpStackReleaseVersion.groovy
  .ci/chatops.groovy
  .ci/fleet-ci-schedule-daily.groovy
  .ci/schedule-daily.groovy
  .ci/schedule-weekly.groovy
  .ci/validateWorkersBeatsCi.groovy
Labels: automation, ci
