Repository elastic/apm-pipeline-library, pull requests merged in 2022-05, with the labels that each got.

#1680 [automation] Update Elastic stack release version source of truth
  resources/versions/releases.properties
Labels: automation, ready-to-merge

#1681 [automation] Update Elastic stack release version 8.2.0 8.2.0
  .ci/packer_cache.sh
  vars/filebeat.groovy
  vars/metricbeat.groovy
Labels: automation, ci, groovy, ready-to-merge, dependency

#1682 print list of files to be linted
  vars/preCommit.groovy
Labels: groovy

#1691 chore: remove deprecated parameter
  src/test/groovy/RunE2EStepTests.groovy
  vars/README.md
  vars/runE2E.groovy
  vars/runE2E.txt
Labels: groovy, Team:Automation

#1689 feat: DinD buildx Docker image
  .ci/docker/dind-buildx/Dockerfile
  .ci/docker/dind-buildx/build-example.sh
  .ci/docker/dind-buildx/config.json
  .ci/docker/dind-buildx/docker-credential-env
  .ci/jobDSL/jobs/apm-ci/apm-shared/docker-images/build_docker_images.groovy
Labels: enhancement, Team:Automation

#1693 automate the bump of beats@main with go 1.17
  .ci/.bump-go-release-version.yml
  .ci/bumpGoReleaseVersion.groovy
Labels: automation, ci

#1695 override go version for fleet-server
  .ci/.bump-go-release-version.yml
Labels: ready-to-merge

#1694 coverage only if entries in the test-coverage.json file
  src/test/groovy/NotifyBuildResultStepTests.groovy
  vars/notifyBuildResult.groovy
Labels: groovy, ready-to-merge

#1690 [automation] Update go release version 1.18.2
  vars/goDefaultVersion.groovy
Labels: automation, groovy, dependency

#1696 jjbb: use github-app-apm-ci credentials
  .ci/jobs/apm-pipeline-library-mbp.yml
  .ci/jobs/apm-test-pipeline-mbp.yml
  .ci/jobs/apm-update-specs-mbp.yml
  .ci/jobs/chatops.yml
  .ci/jobs/ecs-logging-update-specs-mbp.yml
  .ci/jobs/observability-robots-mbp.yml
Labels: chore, ready-to-merge

#1698 withTerraformEnv step
  src/test/groovy/WithTerraformEnvStepTests.groovy
  vars/README.md
  vars/withTerraformEnv.groovy
  vars/withTerraformEnv.txt
Labels: enhancement, groovy

#1699 List existing docker images
  src/test/groovy/PushDockerImagesStepTests.groovy
  vars/pushDockerImages.groovy
Labels: chore, groovy

#1703 core: bump docker image for the jenkins local instance
  local/Dockerfile
Labels: automation, main

#1709 feat: pytest-otel 1.1.0 release notes
  resources/scripts/pytest_otel/CHANGELOG.md
  resources/scripts/pytest_otel/README.md
  resources/scripts/pytest_otel/tests/it/utils/__init__.py
Labels: enhancement, Team:Automation

#1710 docs: update pytest-otel changelog
  resources/scripts/pytest_otel/CHANGELOG.md
  resources/scripts/pytest_otel/setup.cfg
Labels: docs, Team:Automation

#1713 [automation] Update Elastic stack release version source of truth
  resources/versions/releases.properties
Labels: automation
