Repository elastic/apm-pipeline-library, pull requests merged in 2023-03, with the labels that each got.

#2117 updatecli: use GITHUB_RUN_ID for the branch name
  .ci/bump-aliases.yml
  .ci/bump-elastic-stack.yml
  .ci/bump-golang.yml
Labels: automation, ci

#2115 action: is-pr-author-member-elastic-org
  .github/actions/is-pr-author-member-elastic-org/README.md
  .github/actions/is-pr-author-member-elastic-org/action.yml
  .github/workflows/opentelemetry.yml
  .github/workflows/test-is-pr-author-member-elastic-org.yml
Labels: enhancement

#2126 Add check-dependent-jobs action
  .github/actions/check-dependent-jobs/README.md
  .github/actions/check-dependent-jobs/action.yml
  .github/actions/notify-build-status/README.md
  .github/workflows/actions-test.yml
Labels: enhancement

#2130 Add ability to set notification status explicitly
  .github/actions/check-dependent-jobs/README.md
  .github/actions/check-dependent-jobs/action.yml
  .github/actions/notify-build-status/README.md
  .github/actions/notify-build-status/action.yml
Labels: enhancement

#2132 update golang bump to listen for new releases
  .ci/bump-golang.yml
Labels: automation, ci

#2137 [updatecli] Update goDefaultVersion
  vars/goDefaultVersion.groovy
Labels: groovy, dependencies

#2138 updatecli: use default pattern and honour title
  .ci/bump-golang.yml
Labels: automation, ci

#2133 action: deploy-my-kibana
  .github/actions/deploy-my-kibana/README.md
  .github/actions/deploy-my-kibana/action.yml
Labels: enhancement

#2143 action: use deploykibana
  .github/actions/deploy-my-kibana/action.yml
Labels: chore

#2148 dependabot enabled for the github actions composite
  .github/dependabot.yml
Labels: automation

#2164 [automation] Update Elastic stack release version source of truth
  resources/versions/releases.properties
Labels: automation

#2165 [updatecli] Bump elastic stack version to 8.7.0
  vars/filebeat.groovy
  vars/metricbeat.groovy
Labels: groovy, dependencies
