Repository elastic/apm-pipeline-library, pull requests merged in 2023-04, with the labels that each got.

#2167 action: add PR and cluster in the deploy-my-kibana
  .github/actions/deploy-my-kibana/action.yml
Labels: chore

#2178 chore: set APM environment to CI
  .github/actions/oblt-cli/action.yml
Labels: chore

#2190 [Automation] Bump Golang version to 1.20.3
  vars/goDefaultVersion.groovy
Labels: groovy, dependencies

#2198 updatecli and mergify: automate delete branches and when to reuse PRs
  .mergify.yml
  updatecli/updatecli.d/bump-aliases.yml
  updatecli/updatecli.d/bump-elastic-stack.yml
  updatecli/updatecli.d/bump-golang.yml
Labels: chore

#2200 snapshots: when release branch is not yet available in the Unified Release
  .ci/generate-snapshots.sh
Labels: bug, automation, ci
