Repository elastic/apm-pipeline-library, pull requests merged in 2023-02, with the labels that each got.

#2047 Use updatecli for bumping the golang version
  .ci/.bump-go-release-version.yml
  .ci/bump-go-release-version.sh
  .ci/bump-golang.yml
  .github/workflows/bump-golang.yml
Labels: automation, ci

#2054 ci: remove golang auto bump
  .ci/.bump-go-release-version.yml
  .ci/bumpGoReleaseVersion.groovy
  .ci/jobs/bump-go-release-version-pipeline.yml
  .ci/schedule-weekly.groovy
Labels: automation, ci

#2055 ci: remove daily for the syncup and gh populate pipelines
  .ci/githubSyncupLabelsObsDev.groovy
  .ci/jobs/github-syncup-labels-obs-dev-pipeline.yml
  .ci/jobs/populate-github.yml
  .ci/populateGithub.groovy
  .ci/schedule-daily.groovy
Labels: automation, ci

#2039 bump version to use 1.2 so we know that we are moving out of Jenkins
  pom.xml
Labels: ci

#2057 ci: remove jobdsl, ci metrics and test Beats CI
  .ci/fleet-ci-jobdsl-generator.groovy
  .ci/fleet-ci-schedule-daily.groovy
  .ci/jobDSL/README.md
  .ci/jobDSL/build.gradle
  .ci/jobDSL/gradle.properties
  .ci/jobDSL/gradle/wrapper/gradle-wrapper.jar
  .ci/jobDSL/gradle/wrapper/gradle-wrapper.properties
  .ci/jobDSL/gradlew
  .ci/jobDSL/gradlew.bat
  .ci/jobDSL/jobs/apm-ci/apm-shared/folder.groovy
  .ci/jobDSL/jobs/apm-ci/folder.groovy
  .ci/jobDSL/jobs/fleet-ci/fleet-shared/fleet_schedule_daily.groovy
  .ci/jobDSL/jobs/fleet-ci/fleet-shared/gather_ci_metrics_pipeline.groovy
  .ci/jobDSL/jobs/fleet-ci/folder.groovy
  .ci/jobDSL/jobs/fleet-ci/k8s/apm_agent_java_mbp.groovy
  .ci/jobDSL/jobs/fleet-ci/k8s/integrations_mbp.groovy
  .ci/jobDSL/src/test/groovy/JobScriptsSpec.groovy
  .ci/jobDSL/src/test/groovy/hudson/CustomJenkinsRule.groovy
  .ci/jobDSL/src/test/groovy/hudson/CustomPluginManager.groovy
  .ci/jobDSL/templates/mbp.groovy.j2
  .ci/jobDSL/templates/pipeline.groovy.j2
  .ci/jobdsl-generator.groovy
  .ci/jobs/gather-ci-metrics-pipeline.yml
  .ci/schedule-daily.groovy
  .ci/validateWorkersBeatsCi.groovy
  .github/dependabot.yml
  .github/workflows/job-dsl.yml
  .gitignore
  .pre-commit-config.yaml
Labels: automation, ci

#2059 dependabot: remove maven
  .github/dependabot.yml
Labels: automation

#2065 [automation] Update Elastic stack release version source of truth
  resources/versions/releases.properties
Labels: automation

#2066 docker: enable apm-integration-testing-all
  .ci/.docker-images.yml
Labels: automation

#2072 remove: weekly notifications for stalled bumps(elastic stack snapshot)
  .ci/schedule-weekly.groovy
  resources/scripts/generate-email-template-if-no-recent-changes.sh
Labels: automation, ci

#2073 ci: remove daily jobs
  .ci/jobs/apm-schedule-daily.yml
  .ci/schedule-daily.groovy
Labels: automation, ci

#2071 automation: remove snapshot in Jenkins
  .ci/.bump-stack-version.yml
  .ci/bumpStackVersion.groovy
  .ci/jobs/bump-stack-version-pipeline.yml
  .ci/schedule-weekly.groovy
Labels: automation, ci

#2074 ci: remove weekly
  .ci/.weekly-tests-email.yml
  .ci/jobs/apm-schedule-weekly.yml
  .ci/schedule-weekly.groovy
  resources/flaky-watcher.json
Labels: automation, ci

#2075 test-infra: remove those tests and references
  local/configs/jenkins.yaml
  pytest.ini
  resources/JenkinsfileTemplate.groovy
  resources/scripts/jenkins/apm-ci/test-baremetal.sh
  resources/scripts/jenkins/apm-ci/test-mac.sh
  resources/scripts/jenkins/apm-ci/test.ps1
  resources/scripts/jenkins/apm-ci/test.sh
  resources/scripts/jenkins/beats-ci/test-mac.sh
  resources/scripts/jenkins/beats-ci/test.ps1
  resources/scripts/jenkins/beats-ci/test.sh
  resources/scripts/jenkins/build.bat
  resources/scripts/jenkins/build.sh
  test-infra/README.md
  test-infra/apm-ci/test_installed_tools.py
  test-infra/apm-ci/test_installed_tools_docker.py
  test-infra/apm-ci/test_installed_tools_extra.py
  test-infra/apm-ci/test_packer.py
  test-infra/apm-ci/test_windows.py
  test-infra/apm-ci/test_windows_extra.py
  test-infra/beats-ci/test_beats_installed_tools.py
  test-infra/beats-ci/test_beats_packer.py
  test-infra/beats-ci/test_beats_windows.py
Labels: groovy, main

#2080 pre-commit: remove jjbb and jenkinsfile linters
  .pre-commit-config.yaml
Labels: chore

#2084 action: it's required to pass those secrets
  .github/actions/updatecli/action.yml
Labels: bug

#2085 action: bump-aliases use docker login
  .ci/bump-aliases.yml
  .github/actions/docker-login/action.yml
  .github/actions/updatecli/action.yml
Labels: automation, ci

#2086 [automation] Update Elastic stack release version source of truth
  resources/versions/releases.properties
Labels: automation

#2089 action: is-member-elastic-org composite action
  .github/actions/is-member-elastic-org/README.md
  .github/actions/is-member-elastic-org/action.yml
  .github/workflows/opentelemetry.yml
  .github/workflows/test-is-member-elastic-org.yml
Labels: enhancement

#2093 action: use main version for this repo, enable run workflows manually and use composite actions
  .github/workflows/bump-aliases.yml
  .github/workflows/bump-elastic-stack.yml
  .github/workflows/bump-golang.yml
  .github/workflows/opentelemetry.yml
  .github/workflows/pre-commit.yml
  .github/workflows/publish-docker-images.yml
  .github/workflows/release.yml
  .github/workflows/test-is-member-elastic-org.yml
  .github/workflows/test-reporter.yml
Labels: chore

#2090 action: comment-reaction composite action
  .github/actions/comment-reaction/README.md
  .github/actions/comment-reaction/action.yml
  .github/workflows/test-comment-reaction.yml
Labels: enhancement

#2094 action: workflow event composite action
  .github/actions/workflow-run/README.md
  .github/actions/workflow-run/action.yml
  .github/workflows/test-workflow-run.yml
Labels: enhancement

#2096 action: use GH_TOKEN
  .github/actions/comment-reaction/action.yml
  .github/actions/is-member-elastic-org/action.yml
Labels: chore

#2100 Add ability to add custom message to notify-build-status action
  .github/actions/notify-build-status/README.md
  .github/actions/notify-build-status/action.yml
Labels: enhancement

#2101 Add better notify-build-status example
  .github/actions/notify-build-status/README.md
Labels: docs

#2097 action: oblt-cli action
  .github/actions/oblt-cli/README.md
  .github/actions/oblt-cli/action.yml
  .github/workflows/test-oblt-cli.yml
Labels: enhancement

#2095 bump: tweak conditions for current releases and upcoming patches
  .ci/bump-aliases.yml
  .ci/bump-elastic-stack.yml
Labels: automation, ci

#2102 [automation] Update Elastic stack release version source of truth
  resources/versions/releases.properties
Labels: automation

#2103 [updatecli] Bump elastic stack version to 8.6.2
  vars/filebeat.groovy
  vars/metricbeat.groovy
Labels: groovy, dependencies

#2099 action: oblt-cli-create-ccs composite action
  .github/actions/oblt-cli-create-ccs/README.md
  .github/actions/oblt-cli-create-ccs/action.yml
  .github/workflows/test-oblt-cli-create-ccs.yml
Labels: enhancement
