Repository elastic/apm-pipeline-library, pull requests merged in 2023-12, with the labels that each got.

#2459 [automation] Update Elastic stack release version source of truth
  resources/versions/releases.properties
Labels: automation

#2465 artifacts-api: corner case when main has been built and previous version no
  .ci/generate-snapshots.sh
Labels: automation, ci

#2466 ci: support test-reporting
  .github/workflows/test-reporter.yml
Labels: github_actions

#2475 [automation] Update Elastic stack release version source of truth
  resources/versions/releases.properties
Labels: automation

#2467 action: support list of branches
  .github/actions/elastic-stack-snapshot-branches/README.md
  .github/actions/elastic-stack-snapshot-branches/action.yml
  .github/actions/elastic-stack-snapshot-branches/script.py
Labels: enhancement, github_actions

#2476 fix: sort by semver
  .ci/get-next-minor-version.sh
  resources/scripts/artifacts-api-latest-release-versions.sh
Labels: bug, automation, ci

#2478 [automation] Update Elastic stack release version source of truth
  resources/versions/releases.properties
Labels: automation

#2479 releases: provide api with the google bucket
  .ci/generate-releases.sh
  .github/workflows/generate-elastic-stack-releases.yml
  .github/workflows/opentelemetry.yml
  .gitignore
Labels: enhancement, automation, ci

#2480 release: set GH_TOKEN, add debug traces and notify if failures
  .ci/generate-releases.sh
  .github/workflows/generate-elastic-stack-releases.yml
Labels: bug, automation, ci

#2484 ignore: generated credentials
  .gcloudignore
  .gitignore
Labels: chore
