Repository elastic/apm-pipeline-library, pull requests merged in 2023-05, with the labels that each got.

#2204 [automation] Update Elastic stack release version source of truth
  resources/versions/releases.properties
Labels: automation

#2214 [automation] Update Elastic stack release version source of truth
  resources/versions/releases.properties
Labels: automation

#2222 oblt: support github command for serverless
  .github/actions/deploy-my-kibana/README.md
  .github/actions/deploy-my-kibana/action.yml
Labels: enhancement

#2228 [updatecli] Bump elastic stack version to 8.8.0
  vars/filebeat.groovy
  vars/metricbeat.groovy
Labels: automation, groovy, dependencies

#2229 [automation] Update Elastic stack release version source of truth
  resources/versions/releases.properties
Labels: automation
