Repository elastic/apm-pipeline-library, pull requests merged in 2023-10, with the labels that each got.

#2360 feat: return thread ts
  .github/actions/slack-message/action.yml
Labels: enhancement

#2381 fix: create the arm64 Kibana Docker image for serverless
  .github/actions/kibana-docker-image/build-and-push.sh
Labels: bug

#2382 [Automation] Bump Golang version to 1.21.2
  vars/goDefaultVersion.groovy
Labels: automation, groovy, dependencies

#2387 [updatecli] Bump elastic stack version to 8.10.3
  vars/filebeat.groovy
  vars/metricbeat.groovy
Labels: automation, groovy, dependencies

#2388 [Automation] Bump Golang version to 1.21.3
  vars/goDefaultVersion.groovy
Labels: automation, groovy, dependencies

#2389 updatecli: remove autobump
  .github/workflows/bump-elastic-stack.yml
  .github/workflows/bump-golang.yml
  updatecli/updatecli.d/bump-elastic-stack.yml
  updatecli/updatecli.d/bump-golang.yml
Labels: automation, chore

#2390 updatecli: use groups
  updatecli/updatecli.d/bump-aliases.yml
Labels: bug

#2392 [automation] Update Elastic stack release version source of truth
  resources/versions/releases.properties
Labels: automation, ready-to-merge

#2398 [automation] Update Elastic stack release version source of truth
  resources/versions/releases.properties
Labels: automation

#2397 action: add EphemeralCluster=true
  .github/actions/oblt-cli-create-ccs/action.yml
  .github/actions/oblt-cli-create-custom/action.yml
  .github/actions/oblt-cli-create-serverless/action.yml
Labels: enhancement

#2420 docker: remove apm-integration-testing docker image generation
  .ci/.docker-images.yml
Labels: docker

#2417 dependabot: run weekly on sundays and group by
  .github/dependabot.yml
Labels: automation
