Repository elastic/apm-pipeline-library, pull requests merged in 2023-01, with the labels that each got.

#1986 Migrate build-docker-images to GH Actions Workflow
  .ci/.docker-images.schema.json
  .ci/.docker-images.yml
  .ci/build-docker-images.groovy
  .ci/jobDSL/jobs/apm-ci/apm-shared/docker-images/build_docker_images.groovy
  .ci/jobDSL/jobs/apm-ci/apm-shared/folder.groovy
  .ci/scripts/validate-docker-images-config-yaml.sh
  .github/workflows/publish-docker-images.yml
  .pre-commit-config.yaml
  docs/INTERNAL_DOCKER_IMAGES.md
Labels: automation

#1972 [automation] Update go release version 1.18.9
  vars/goDefaultVersion.groovy
Labels: automation, groovy, dependency

#2000 fix: use observability Vault namespace
  .ci/Jenkinsfile
  .ci/schedule-daily.groovy
  .ci/schedule-weekly.groovy
  resources/scripts/pytest_otel/Makefile
  resources/scripts/pytest_otel/tests/it/test_basic_plugin.py
  resources/scripts/pytest_otel/tests/it/test_failure_code_plugin.py
  resources/scripts/pytest_otel/tests/it/test_failure_plugin.py
  resources/scripts/pytest_otel/tests/it/test_skip_plugin.py
  resources/scripts/pytest_otel/tests/it/test_success_plugin.py
  resources/scripts/pytest_otel/tests/it/test_xfail_no_run_plugin.py
  resources/scripts/pytest_otel/tests/it/test_xfail_plugin.py
  resources/scripts/pytest_otel/tests/it/utils/__init__.py
  src/test/groovy/GetVaultSecretStepTests.groovy
  src/test/resources/jobs/dockerLogin.dsl
  vars/README.md
  vars/codecov.groovy
  vars/codecov.txt
  vars/opbeansPipeline.groovy
  vars/preCommit.groovy
  vars/preCommit.txt
  vars/writeVaultSecret.groovy
  vars/writeVaultSecret.txt
Labels: bug, automation, ci, groovy, Team:Automation

#1985 Add flattenMap
  src/test/groovy/ApmBasePipelineTest.groovy
  src/test/groovy/FlattenMapStepTests.groovy
  vars/flattenMap.groovy
  vars/flattenMap.txt
Labels: groovy

#1976 [automation] Update Elastic stack release version source of truth
  resources/versions/releases.properties
Labels: automation

#2004 [automation] Update Elastic stack release version 8.6.0 8.6.0
  .ci/packer_cache.sh
  vars/filebeat.groovy
  vars/metricbeat.groovy
Labels: automation, ci, groovy, dependency

#2009 action: reusable action for the OTEL export
  .github/actions/opentelemetry/README.md
  .github/actions/opentelemetry/action.yml
Labels: enhancement

#2011 action: composite cannot access to secrets
  .github/actions/opentelemetry/README.md
  .github/actions/opentelemetry/action.yml
Labels: ci

#2015 feat: bump Python OpenTelemetry SDK to 1.15
  resources/scripts/pytest_otel/CHANGELOG.md
  resources/scripts/pytest_otel/README.md
  resources/scripts/pytest_otel/docs/demos/elastic/elastic-stack.yml
  resources/scripts/pytest_otel/mypy.ini
  resources/scripts/pytest_otel/pyproject.toml
  resources/scripts/pytest_otel/requirements.txt
  resources/scripts/pytest_otel/setup.cfg
  resources/scripts/pytest_otel/tox.ini
Labels: enhancement, Team:Automation

#2018 automation: bump version for the apm-integration-testing@main
  .ci/.bump-stack-version.yml
Labels: ci

#2021 fix: Kibana yarn docker image build
  .ci/.docker-images.yml
  .ci/docker/kibana-devmode/Dockerfile
  .ci/docker/kibana-yarn/Dockerfile
Labels: bug

#2022 action: use pre-commit
  .ci/Jenkinsfile
  .github/workflows/opentelemetry.yml
  .github/workflows/pre-commit.yml
  .pre-commit-config.yaml
Labels: automation, ci

#2020 test-infra: remove running it
  .ci/Jenkinsfile
  .gitignore
  resources/JenkinsfileTemplate.groovy
  src/co/elastic/NotificationManager.groovy
Labels: automation, ci, groovy

#2019 action: release with GH actions
  .ci/Jenkinsfile
  .github/workflows/release.yml
  docs/RELEASE.md
  resources/scripts/jenkins/release-perform.sh
Labels: automation, ci

#2025 action: fix missing run
  .github/workflows/release.yml
Labels: ci

#2024 Remove CI pipelines
  .ci/Jenkinsfile
  .ci/beats-webhook.groovy
  .ci/chatops.groovy
  .ci/jobs/apm-pipeline-library-mbp.yml
  .ci/jobs/beats-webhook.yml
  .ci/jobs/chatops.yml
  .ci/jobs/jenkins-git-fetch-reference.yml
  .ci/jobs/jobdsl-generator.yml
Labels: automation, ci

#2026 action: main already exists
  .github/workflows/release.yml
  pom.xml
Labels: ci

#2027 action: use PAT
  .github/workflows/release.yml
Labels: ci

#2028 action: setup-git required for the releases
  .github/workflows/release.yml
Labels: ci

#2017 badge: add snapshoty badge in the GitHub PR comments
  resources/github-comment-markdown.template
  src/co/elastic/NotificationManager.groovy
  src/test/groovy/NotificationManagerStepTests.groovy
Labels: enhancement, groovy

#2029 action: fix permissions in the release
  .github/workflows/release.yml
Labels: ci

#2032 support for golang rc versions
  src/test/groovy/IsBeforeGo1_16StepTests.groovy
  vars/isBeforeGo1_16.groovy
Labels: enhancement, groovy

#2023 [automation] Update Elastic stack release version source of truth
  resources/versions/releases.properties
Labels: automation

#2034 [automation] Update Elastic stack release version 8.6.1 8.6.1
  .ci/packer_cache.sh
  vars/filebeat.groovy
  vars/metricbeat.groovy
Labels: automation, ci, groovy, dependency

#2037 fix precommit defects
  .github/actions/snapshoty/package.json
  .pre-commit-config.yaml
  resources/docs/test.asciidoc
  resources/reviewApproved.json
  resources/runbld/build.json
  resources/runbld/failure.json
  resources/runbld/log.json
  resources/scripts/count-data.sh
  resources/scripts/pytest_apm/pytest_apm.py
  resources/templates/bundlesize.md.j2
  src/co/elastic/Nexus.groovy
  src/co/elastic/beats/BeatsFunction.groovy
  src/test/groovy/BeatsStagesStepTests.groovy
  src/test/groovy/GithubCommentIssueStepTests.groovy
  src/test/groovy/GithubPrLatestCommentStepTests.groovy
  src/test/groovy/HttpRequestStepTests.groovy
  src/test/groovy/IsMemberOfStepTests.groovy
  src/test/groovy/MvnVersionTests.groovy
  src/test/groovy/ReleaseNotificationStepTests.groovy
  src/test/resources/flake-tests-errors-without-match.json
  src/test/resources/jobs/beats/beatsStages.dsl
  src/test/resources/jobs/getBuildInfoJsonFiles/connectionRefused.dsl
  src/test/resources/jobs/getBuildInfoJsonFiles/multiTestFailures.dsl
  src/test/resources/jobs/githubCheck.dsl
  vars/withAPM.groovy
Labels: groovy
