Repository elastic/apm-pipeline-library, pull requests merged in 2023-11, with the labels that each got.

#2424 fix: parameters when using ccs
  .github/actions/oblt-cli-create-ccs/action.yml
Labels: bug

#2425 feat: fetch credentials from the given cluster
  .github/actions/oblt-cli-cluster-credentials/README.md
  .github/actions/oblt-cli-cluster-credentials/action.yml
  .github/actions/setup-oblt-cli/action.yml
  .github/dependabot.yml
  .github/workflows/test-oblt-cli-cluster-credentials.yml
Labels: enhancement, automation

#2427 feat: destroy any given cluster
  .github/actions/oblt-cli-destroy-cluster/README.md
  .github/actions/oblt-cli-destroy-cluster/action.yml
  .github/dependabot.yml
Labels: enhancement, automation, github_actions

#2426 chore: remove docker build for obsoleted elastic-apps
  .ci/.docker-images.yml
Labels: chore

#2428 feat: add support for a new input called cluster-info-file
  .github/actions/oblt-cli-cluster-credentials/README.md
  .github/actions/oblt-cli-cluster-credentials/action.yml
  .github/actions/oblt-cli-cluster-name-validation/README.md
  .github/actions/oblt-cli-cluster-name-validation/action.yml
  .github/actions/oblt-cli-destroy-cluster/README.md
  .github/actions/oblt-cli-destroy-cluster/action.yml
  .github/dependabot.yml
  .github/workflows/test-oblt-cli-cluster-name-validation.yml
Labels: enhancement, automation, github_actions

#2431 [automation] Update Elastic stack release version source of truth
  resources/versions/releases.properties
Labels: automation

#2433 secret: update the buildkite api access token
  .github/actions/buildkite/action.yml
Labels: enhancement

#2436 update-cli: workflow link is now supported natively
  .github/workflows/bump-aliases.yml
  updatecli/updatecli.d/bump-aliases.yml
Labels: enhancement

#2437 [automation] Update Elastic stack release version source of truth
  resources/versions/releases.properties
Labels: automation

#2438 fix: name of the serverless qa environment
  .github/actions/deploy-my-kibana/action.yml
Labels: bug

#2447 chore: add details about keep_serverless-qa-oblt
  .github/actions/deploy-my-kibana/action.yml
Labels: docs

#2449 docker-images: update to reflect what we use these days
  .ci/.docker-images.yml
Labels: automation

#2448 chore: support serverless regardless of the branch
  .github/actions/deploy-my-kibana/action.yml
Labels: chore

#2451 action(buildkite): fix empty buildenvs parameter
  .github/actions/buildkite/run.sh
Labels: bug

#2450 action(buildkite): backward compatible
  .github/actions/buildkite/README.md
  .github/actions/buildkite/action.yml
Labels: bug

#2452 actions: add read permission
  .github/workflows/opentelemetry.yml
  .github/workflows/test-comment-reaction.yml
  .github/workflows/test-deploy-my-kibana.yml
  .github/workflows/test-elastic-stack-snapshot-branches.yml
  .github/workflows/test-is-member-elastic-org.yml
  .github/workflows/test-is-pr-author-member-elastic-org.yml
  .github/workflows/test-kibana-docker-image-action.yml
  .github/workflows/test-oblt-cli-cluster-credentials.yml
  .github/workflows/test-oblt-cli-cluster-name-validation.yml
  .github/workflows/test-oblt-cli-create-ccs.yml
  .github/workflows/test-oblt-cli-create-custom.yml
  .github/workflows/test-oblt-cli-create-serverless.yml
  .github/workflows/test-oblt-cli.yml
  .github/workflows/test-reporter.yml
  .github/workflows/test-workflow-run.yml
Labels: chore, github_actions
