Repository elastic/apm-pipeline-library, pull requests merged in 2024-05, with the labels that each got.

#2595 github-action: undeploy my kibana
  .github/actions/undeploy-my-kibana/README.md
  .github/actions/undeploy-my-kibana/action.yml
Labels: enhancement

#2599 github-action: use the right contract for destroying PRs
  .github/actions/undeploy-my-kibana/action.yml
Labels: bug

#2601 [automation] Update Elastic stack release version source of truth
  resources/versions/releases.properties
Labels: automation

#2602 github-action: configure username for destroy cluster
  .github/actions/oblt-cli-destroy-cluster/README.md
  .github/actions/oblt-cli-destroy-cluster/action.yml
Labels: enhancement, github_actions

#2603 jenkins: disable send telemetry data by default
  .github/workflows/pytest_otel.yml
  src/test/groovy/NotifyBuildResultStepTests.groovy
  vars/notifyBuildResult.groovy
  vars/notifyBuildResult.txt
Labels: enhancement, groovy

#2605 fix(buildkite): run cancelled step before tearing down the secret
  .github/actions/buildkite/action.yml
Labels: bug, github_actions

#2606 github-actions: run faster builds if no jenkins
  .github/workflows/build-test-no-jenkins.yml
  .github/workflows/build-test.yml
Labels: chore, github_actions

#2594 dependabot: use directories
  .github/dependabot.yml
Labels: automation, dependencies

#2610 [automation] Update Elastic stack release version source of truth
  resources/versions/releases.properties
Labels: automation

#2611 fix dependabot
  .github/dependabot.yml
Labels: automation

#2612 github-actions: disable kibana serverless validation
  .github/workflows/test-kibana-docker-image-action.yml
Labels: enhancement

#2613 ci: use updatecli with github secrets
  .github/workflows/bump-aliases.yml
  updatecli/updatecli.d/bump-aliases.yml
Labels: enhancement, github_actions
