Repository elastic/apm-pipeline-library, pull requests merged in 2024-03, with the labels that each got.

#2555 fix: linting issues
  .github/workflows/lint.yml
  .github/workflows/publish-docker-images.yml
  .github/workflows/test-oblt-cli-cluster-credentials.yml
Labels: bug, github_actions

#2553 oblt-cli: pin version 6.5.3
  .github/actions/oblt-cli-cluster-credentials/action.yml
  .github/actions/setup-oblt-cli/download.sh
Labels: enhancement

#2554 github-action(buildkite): retry curl if failures and avoid failing if errors with logs
  .github/actions/buildkite/run.sh
Labels: bug

#2563 fix: avoid unexpected versions for the time being
  .ci/get-next-minor-version.sh
Labels: automation, ci, chore

#2564 action: env variables are required for functional-opbeans
  .github/workflows/publish-docker-images.yml
Labels: bug

#2570 [automation] Update Elastic stack release version source of truth
  resources/versions/releases.properties
Labels: automation
