Repository elastic/apm-pipeline-library, pull requests merged in 2024-02, with the labels that each got.

#2520 fix: github API comment is different when modigying an existing one
  vars/githubTraditionalPrComment.groovy
Labels: bug, groovy

#2523 Update docs-preview link
  vars/notifyBuildResult.groovy
Labels: groovy

#2524 [automation] Update Elastic stack release version source of truth
  resources/versions/releases.properties
Labels: automation

#2544 Added action to wait for maven-central artifacts to be available
  .github/actions/await-maven-artifact/action.yml
  .gitignore
Labels: enhancement

#2546 [automation] Update Elastic stack release version source of truth
  resources/versions/releases.properties
Labels: automation

#2545 docs: github actions
  .github/actions/await-maven-artifact/README.md
  .github/actions/docker-login/README.md
  .github/actions/github-token/README.md
  .github/actions/github-token/action.yml
  .github/actions/is-member-elastic-org/README.md
  .github/actions/is-member-elastic-org/action.yml
  .github/actions/setup-git/README.md
  .github/actions/setup-vault-cli/README.md
  .github/actions/slack-message/README.md
  .github/actions/slack-message/action.yml
Labels: docs

#2547 github-action: use phoenix-actions/test-reporting@v12
  .github/actions/test-report/action.yml
Labels: enhancement

#2549 [automation] Update Elastic stack release version source of truth
  resources/versions/releases.properties
Labels: automation
